package tle

// AUTO-GENERATED - DO NOT EDIT
// Generated by: go run circuits/tle/cmd/genkey/main.go
// This file contains the embedded proving and verifying keys from trusted setup
// VK Hash: d31492395661639f3905579905863036

import _ "embed"

//go:embed vk.bin
var EmbeddedVK []byte

// CircuitID is the SHA256 hash of the VK (first 16 bytes hex)
const CircuitID = "d31492395661639f3905579905863036"

// FullVKHash is the complete SHA256 hash of the VK
const FullVKHash = "d31492395661639f39055799058630369dc19b32d7440f5813de76705a04baa4"
