package commitment

// AUTO-GENERATED - DO NOT EDIT
// Generated by: go run circuits/commitment/cmd/genkey/main.go
// This file contains the embedded proving and verifying keys from trusted setup
// VK Hash: f09603850068bf68fcb256838cc7d617

import _ "embed"

//go:embed vk.bin
var EmbeddedVK []byte

//go:embed pk.bin
var EmbeddedPK []byte

// CircuitID is the SHA256 hash of the VK (first 16 bytes hex)
const CircuitID = "f09603850068bf68fcb256838cc7d617"

// FullVKHash is the complete SHA256 hash of the VK
const FullVKHash = "f09603850068bf68fcb256838cc7d617edb21a0f285044c7a4d1abf1bc8882a4"
